#!/usr/bin/env python3
"""Populate the Notion Skills Registry database with all installed agent skills."""

import os
import sys
from notion_client import Client

NOTION_API_KEY = os.environ.get("NOTION_API_KEY")
if not NOTION_API_KEY:
    print("ERROR: NOTION_API_KEY not set")
    sys.exit(1)

# Database ID from creation step
DB_ID = "68aeb7e6-a425-44b8-848b-c8be1d921004"

notion = Client(auth=NOTION_API_KEY)

BASE = "/Users/tulioferro"

SKILLS = [
    # ─── Writing Skills (custom, both platforms) ───────────────────────────────
    {
        "Name": "professional-writer",
        "Description": "Write professional documents: assessment reports, PRDs, emails, executive briefs, strategic memos, LinkedIn posts, project status reports. Covers all business writing for Live Engine & CTA.",
        "Category": "Writing",
        "Platform": "Both",
        "Status": "Invoke-When-Needed",
        "Location": "agents-project",
        "File Path": f"{BASE}/.openclaw/workspace/.agents/skills/professional-writer/SKILL.md",
        "Version": "1.1.0",
        "Tags": ["writing", "reports"],
    },
    {
        "Name": "event-brief",
        "Description": "Live event production documents: full production brief, run of show, tech rider, crew & vendor sheet. For Live Engine events and entertainment productions.",
        "Category": "Writing",
        "Platform": "Both",
        "Status": "Invoke-When-Needed",
        "Location": "agents-project",
        "File Path": f"{BASE}/.openclaw/workspace/.agents/skills/event-brief/SKILL.md",
        "Version": "1.0.0",
        "Tags": ["writing", "production"],
    },
    {
        "Name": "sow-writer",
        "Description": "Statement of Work, project charter, change order documents. For consulting engagements, client projects, and Creative Tools Agency deliverables.",
        "Category": "Writing",
        "Platform": "Both",
        "Status": "Invoke-When-Needed",
        "Location": "agents-project",
        "File Path": f"{BASE}/.openclaw/workspace/.agents/skills/sow-writer/SKILL.md",
        "Version": "1.0.0",
        "Tags": ["writing"],
    },
    {
        "Name": "proposal-writer",
        "Description": "Client proposals, RFP responses, capability statements. For CTA and Live Engine business development and client acquisition.",
        "Category": "Writing",
        "Platform": "Both",
        "Status": "Invoke-When-Needed",
        "Location": "agents-project",
        "File Path": f"{BASE}/.openclaw/workspace/.agents/skills/proposal-writer/SKILL.md",
        "Version": "1.0.0",
        "Tags": ["writing"],
    },
    {
        "Name": "weekly-review",
        "Description": "Weekly operational review: wins, blockers, priorities, resource status, and next-week plan. Structured format for business rhythm reporting.",
        "Category": "Writing",
        "Platform": "Both",
        "Status": "Invoke-When-Needed",
        "Location": "agents-project",
        "File Path": f"{BASE}/.openclaw/workspace/.agents/skills/weekly-review/SKILL.md",
        "Version": "1.0.0",
        "Tags": ["writing", "reports", "review"],
    },
    {
        "Name": "research-digest",
        "Description": "Convert raw research into structured digests: TL;DR, signal summary, implications, open questions. For intelligence briefs and research synthesis.",
        "Category": "Writing",
        "Platform": "Both",
        "Status": "Invoke-When-Needed",
        "Location": "agents-project",
        "File Path": f"{BASE}/.openclaw/workspace/.agents/skills/research-digest/SKILL.md",
        "Version": "1.0.0",
        "Tags": ["writing", "digest"],
    },
    # ─── PR / Git Workflow (agents-project) ─────────────────────────────────
    {
        "Name": "merge-pr",
        "Description": "Merge pull requests with proper checks: verify CI passes, resolve conflicts, squash or merge based on repo conventions.",
        "Category": "Coding/Engineering",
        "Platform": "Both",
        "Status": "Active",
        "Location": "agents-project",
        "File Path": f"{BASE}/.openclaw/workspace/.agents/skills/merge-pr/SKILL.md",
        "Version": "",
        "Tags": ["pr-workflow", "git"],
    },
    {
        "Name": "prepare-pr",
        "Description": "Prepare and open a pull request: stage changes, write PR title and description, assign reviewers, add labels.",
        "Category": "Coding/Engineering",
        "Platform": "Both",
        "Status": "Active",
        "Location": "agents-project",
        "File Path": f"{BASE}/.openclaw/workspace/.agents/skills/prepare-pr/SKILL.md",
        "Version": "",
        "Tags": ["pr-workflow", "git"],
    },
    {
        "Name": "review-pr",
        "Description": "Conduct structured code review on a pull request: check logic, style, tests, and security. Outputs inline comments and summary.",
        "Category": "Coding/Engineering",
        "Platform": "Both",
        "Status": "Active",
        "Location": "agents-project",
        "File Path": f"{BASE}/.openclaw/workspace/.agents/skills/review-pr/SKILL.md",
        "Version": "",
        "Tags": ["pr-workflow", "git", "review"],
    },
    # ─── Tulsbot-injected active skills (agents-project) ────────────────────
    {
        "Name": "notebooklm",
        "Description": "Query Google NotebookLM notebooks for deep research synthesis and source-grounded answers.",
        "Category": "Intelligence/AI",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "agents-project",
        "File Path": f"{BASE}/.openclaw/workspace/.agents/skills/notebooklm/SKILL.md",
        "Version": "",
        "Tags": ["ai-tools"],
    },
    {
        "Name": "mintlify",
        "Description": "Generate and update Mintlify documentation: write MDX pages, update nav, and sync with code.",
        "Category": "Coding/Engineering",
        "Platform": "Both",
        "Status": "Active",
        "Location": "agents-project",
        "File Path": f"{BASE}/.openclaw/workspace/.agents/skills/mintlify/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    # ─── Tulsbot workspace skills ────────────────────────────────────────────
    {
        "Name": "morning-briefing",
        "Description": "Generate morning briefing: pending tasks, calendar, news summary, and priority actions for the day.",
        "Category": "Productivity",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/morning-briefing/SKILL.md",
        "Version": "",
        "Tags": ["ops"],
    },
    {
        "Name": "mission-control",
        "Description": "High-level workspace status: running agents, active tasks, blockers, memory health, and system pulse.",
        "Category": "System/Ops",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/mission-control/SKILL.md",
        "Version": "",
        "Tags": ["ops"],
    },
    {
        "Name": "daily-rhythm",
        "Description": "Enforce Tulsbot's daily operational rhythm: morning sync, midday check-in, EOD wrap, and nightly memory compaction.",
        "Category": "System/Ops",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/daily-rhythm/SKILL.md",
        "Version": "",
        "Tags": ["ops", "memory"],
    },
    {
        "Name": "memory-hygiene",
        "Description": "Audit and clean Tulsbot's memory tiers: deduplicate, promote high-value entries, archive stale ones.",
        "Category": "System/Ops",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/memory-hygiene/SKILL.md",
        "Version": "",
        "Tags": ["memory", "ops"],
    },
    {
        "Name": "ops-hygiene",
        "Description": "Workspace operational hygiene: check services, clear stale locks, rotate logs, and verify environment configs.",
        "Category": "System/Ops",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/ops-hygiene/SKILL.md",
        "Version": "",
        "Tags": ["ops"],
    },
    {
        "Name": "self-monitor",
        "Description": "Tulsbot introspection: log own state, detect reasoning drift, report decision quality, and flag anomalies.",
        "Category": "System/Ops",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/self-monitor/SKILL.md",
        "Version": "",
        "Tags": ["ops"],
    },
    {
        "Name": "context-recovery",
        "Description": "Recover session context after reset or crash: read handoff doc, replay transcript, and restore working state.",
        "Category": "System/Ops",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/context-recovery/SKILL.md",
        "Version": "",
        "Tags": ["memory", "ops"],
    },
    {
        "Name": "self-improving-agent",
        "Description": "Tulsbot self-improvement loop: identify capability gaps, propose skill updates, and apply improvements after approval.",
        "Category": "Intelligence/AI",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/self-improving-agent/SKILL.md",
        "Version": "",
        "Tags": ["ai-tools"],
    },
    {
        "Name": "summarize",
        "Description": "Summarize documents, conversations, or pages into structured bullet-point digests with key decisions and action items.",
        "Category": "Intelligence/AI",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/summarize/SKILL.md",
        "Version": "",
        "Tags": ["ai-tools", "digest"],
    },
    {
        "Name": "supabase-ops",
        "Description": "Query and manage Supabase tables: run SQL, insert/update rows, manage storage buckets and RLS policies.",
        "Category": "Notion/Data",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/supabase-ops/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "systematic-debugging",
        "Description": "Structured debugging protocol: reproduce issue, isolate root cause, enumerate hypotheses, apply fix, and verify.",
        "Category": "Coding/Engineering",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/systematic-debugging/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "verification-before-completion",
        "Description": "Before claiming work is done: run verification commands, confirm output, and prevent false success claims.",
        "Category": "Coding/Engineering",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/verification-before-completion/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "writing-plans",
        "Description": "Write structured implementation plans before touching code: goals, phases, tasks, risks, and verification steps.",
        "Category": "Productivity",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/writing-plans/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "taskr",
        "Description": "Manage tasks in Tulsbot's task system: create, update, prioritize, and close tasks with proper metadata.",
        "Category": "Productivity",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/taskr/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "structured-reports",
        "Description": "Generate structured operational reports: current state, issues, root causes, proposed solutions, recommendations.",
        "Category": "Writing",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/structured-reports/SKILL.md",
        "Version": "",
        "Tags": ["writing", "reports"],
    },
    {
        "Name": "weekly-report-generator",
        "Description": "Auto-generate weekly Tulsbot operational report: tasks completed, blockers, memory stats, and next-week priorities.",
        "Category": "Writing",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/weekly-report-generator/SKILL.md",
        "Version": "",
        "Tags": ["writing", "reports"],
    },
    {
        "Name": "git-summary",
        "Description": "Summarize recent git activity: commits, PRs, branches, and code changes in a readable format.",
        "Category": "Coding/Engineering",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/git-summary/SKILL.md",
        "Version": "",
        "Tags": ["git"],
    },
    {
        "Name": "commit-analyzer",
        "Description": "Analyze commit history for patterns, velocity, hotspots, and code quality trends.",
        "Category": "Coding/Engineering",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/commit-analyzer/SKILL.md",
        "Version": "",
        "Tags": ["git"],
    },
    {
        "Name": "conventional-commits",
        "Description": "Enforce Conventional Commits spec: parse, validate, and generate commit messages in the correct format.",
        "Category": "Coding/Engineering",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/conventional-commits/SKILL.md",
        "Version": "",
        "Tags": ["git"],
    },
    {
        "Name": "dep-audit",
        "Description": "Audit dependencies for vulnerabilities, outdated packages, and license issues across npm, pip, and other ecosystems.",
        "Category": "DevOps",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/dep-audit/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "gh-address-comments",
        "Description": "Address review comments on GitHub PRs: parse feedback, apply fixes, and respond to reviewers.",
        "Category": "Coding/Engineering",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/gh-address-comments/SKILL.md",
        "Version": "",
        "Tags": ["pr-workflow", "git"],
    },
    {
        "Name": "linear",
        "Description": "Manage Linear issues, projects, and team workflows: create, update, prioritize, and triage tickets.",
        "Category": "Productivity",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/linear/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "organize-agent-chats",
        "Description": "Manage Cursor/Tulsbot chat sessions: registry, numbering, archive SOP, handoff, transcript export.",
        "Category": "Productivity",
        "Platform": "Both",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/organize-agent-chats/SKILL.md",
        "Version": "",
        "Tags": ["memory"],
    },
    {
        "Name": "notion-knowledge-capture",
        "Description": "Capture conversations and decisions into structured Notion pages: wiki entries, how-tos, decisions, FAQs.",
        "Category": "Notion/Data",
        "Platform": "Both",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/notion-knowledge-capture/SKILL.md",
        "Version": "",
        "Tags": ["notion"],
    },
    {
        "Name": "notion-meeting-intelligence",
        "Description": "Prepare meeting materials with Notion context: gather attendee info, draft agendas and pre-reads.",
        "Category": "Notion/Data",
        "Platform": "Both",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/notion-meeting-intelligence/SKILL.md",
        "Version": "",
        "Tags": ["notion"],
    },
    {
        "Name": "notion-research-documentation",
        "Description": "Research across Notion and synthesize into structured documentation: briefs, comparisons, reports with citations.",
        "Category": "Notion/Data",
        "Platform": "Both",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/notion-research-documentation/SKILL.md",
        "Version": "",
        "Tags": ["notion", "digest"],
    },
    {
        "Name": "notion-spec-to-implementation",
        "Description": "Turn Notion specs into implementation plans, tasks, and progress tracking from PRDs/feature specs.",
        "Category": "Notion/Data",
        "Platform": "Both",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/notion-spec-to-implementation/SKILL.md",
        "Version": "",
        "Tags": ["notion"],
    },
    {
        "Name": "qmd",
        "Description": "Search markdown knowledge bases, notes, and documentation using QMD BM25/vector search.",
        "Category": "Intelligence/AI",
        "Platform": "Both",
        "Status": "Active",
        "Location": "tulsbot-workspace",
        "File Path": f"{BASE}/.openclaw/workspace-tulsbot/skills/qmd/SKILL.md",
        "Version": "",
        "Tags": ["ai-tools", "memory"],
    },
    # ─── Core skills (.openclaw/skills/) ─────────────────────────────────────
    {
        "Name": "humanizer-1.0.0",
        "Description": "Humanize AI-generated text for external communications: reduce robotic tone, add natural cadence, preserve meaning.",
        "Category": "Writing",
        "Platform": "Both",
        "Status": "Active",
        "Location": "skills-core",
        "File Path": f"{BASE}/.openclaw/skills/humanizer-1.0.0/SKILL.md",
        "Version": "1.0.0",
        "Tags": ["writing"],
    },
    {
        "Name": "humanize-ai-text-1.0.1",
        "Description": "Advanced AI text humanizer: rephrase for naturalness, vary sentence structure, and avoid detection patterns.",
        "Category": "Writing",
        "Platform": "Both",
        "Status": "Active",
        "Location": "skills-core",
        "File Path": f"{BASE}/.openclaw/skills/humanize-ai-text-1.0.1/SKILL.md",
        "Version": "1.0.1",
        "Tags": ["writing"],
    },
    {
        "Name": "notion-1.0.0",
        "Description": "Notion API operations: query databases, create/update pages, add blocks, manage integrations.",
        "Category": "Notion/Data",
        "Platform": "Both",
        "Status": "Active",
        "Location": "skills-core",
        "File Path": f"{BASE}/.openclaw/skills/notion-1.0.0/SKILL.md",
        "Version": "1.0.0",
        "Tags": ["notion"],
    },
    {
        "Name": "clawddocs-1.2.2",
        "Description": "OpenClaw documentation generator: build, update, and publish docs from code and configuration.",
        "Category": "Coding/Engineering",
        "Platform": "Tulsbot",
        "Status": "Active",
        "Location": "skills-core",
        "File Path": f"{BASE}/.openclaw/skills/clawddocs-1.2.2/SKILL.md",
        "Version": "1.2.2",
        "Tags": [],
    },
    # ─── Cursor skills (.cursor/skills/) ──────────────────────────────────────
    {
        "Name": "notion-master-controller",
        "Description": "Expert Notion agent: reads, creates, modifies, deletes pages/databases/blocks; controls Mac app via AppleScript.",
        "Category": "Notion/Data",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "cursor-skills",
        "File Path": f"{BASE}/.cursor/skills/notion-master-controller/SKILL.md",
        "Version": "",
        "Tags": ["notion"],
    },
    {
        "Name": "organize-agent-chats (Cursor)",
        "Description": "Cursor chat session management: registry, archive SOP, handoff, transcript export, and session continuity.",
        "Category": "Productivity",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "cursor-skills",
        "File Path": f"{BASE}/.cursor/skills/organize-agent-chats/SKILL.md",
        "Version": "",
        "Tags": ["memory"],
    },
    {
        "Name": "create-skill (Cursor)",
        "Description": "Guide to creating effective Agent Skills for Cursor: structure, best practices, SKILL.md format.",
        "Category": "System/Ops",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "cursor-skills",
        "File Path": f"{BASE}/.cursor/skills-cursor/create-skill/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "create-rule (Cursor)",
        "Description": "Create Cursor rules for persistent AI guidance: coding standards, project conventions, file-specific patterns.",
        "Category": "System/Ops",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "cursor-skills",
        "File Path": f"{BASE}/.cursor/skills-cursor/create-rule/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    # ─── Codex skills (.codex/skills/) ────────────────────────────────────────
    {
        "Name": "vercel-deploy",
        "Description": "Deploy applications and websites to Vercel with CLI and project configuration.",
        "Category": "DevOps",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/vercel-deploy/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "cloudflare-deploy",
        "Description": "Deploy to Cloudflare Workers and Pages.",
        "Category": "DevOps",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/cloudflare-deploy/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "render-deploy",
        "Description": "Deploy applications to Render: analyze codebase, generate render.yaml Blueprints.",
        "Category": "DevOps",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/render-deploy/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "playwright",
        "Description": "Browser automation via Playwright: navigation, form filling, snapshots, screenshots, data extraction.",
        "Category": "Coding/Engineering",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/playwright/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "sentry",
        "Description": "Inspect Sentry issues/events, summarize production errors, pull health data via Sentry API.",
        "Category": "Coding/Engineering",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/sentry/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "openai-docs",
        "Description": "Up-to-date OpenAI product and API documentation: Codex, Responses API, Chat Completions, Agents SDK, Realtime.",
        "Category": "Intelligence/AI",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/openai-docs/SKILL.md",
        "Version": "",
        "Tags": ["ai-tools"],
    },
    {
        "Name": "sora",
        "Description": "Generate, remix, poll, list, download, delete Sora videos via OpenAI video API.",
        "Category": "Intelligence/AI",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/sora/SKILL.md",
        "Version": "",
        "Tags": ["ai-tools"],
    },
    {
        "Name": "speech",
        "Description": "Text-to-speech narration and voiceover via OpenAI Audio API with built-in voices.",
        "Category": "Intelligence/AI",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/speech/SKILL.md",
        "Version": "",
        "Tags": ["ai-tools"],
    },
    {
        "Name": "transcribe",
        "Description": "Transcribe audio files to text with optional diarization and known-speaker hints.",
        "Category": "Intelligence/AI",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/transcribe/SKILL.md",
        "Version": "",
        "Tags": ["ai-tools"],
    },
    {
        "Name": "security-threat-model",
        "Description": "Repository-grounded threat modeling: trust boundaries, assets, attacker capabilities, abuse paths, mitigations.",
        "Category": "Coding/Engineering",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/security-threat-model/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "spreadsheet",
        "Description": "Create, edit, analyze, and format spreadsheets (.xlsx, .csv) with openpyxl and pandas.",
        "Category": "Productivity",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/spreadsheet/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "pdf",
        "Description": "Read, create, and review PDF files with visual rendering via Poppler, reportlab, pdfplumber.",
        "Category": "Productivity",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/pdf/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "doc",
        "Description": "Read, create, and edit .docx documents with formatting fidelity using python-docx.",
        "Category": "Productivity",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/doc/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "screenshot",
        "Description": "Desktop or system screenshots: full screen, specific app/window, or pixel region via OS-level capture.",
        "Category": "Productivity",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/screenshot/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "gh-address-comments (Codex)",
        "Description": "Address review/issue comments on open GitHub PRs using gh CLI.",
        "Category": "Coding/Engineering",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/gh-address-comments/SKILL.md",
        "Version": "",
        "Tags": ["pr-workflow", "git"],
    },
    {
        "Name": "linear (Codex)",
        "Description": "Manage Linear issues, projects, and team workflows from Cursor/tulsCodex.",
        "Category": "Productivity",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/linear/SKILL.md",
        "Version": "",
        "Tags": [],
    },
    {
        "Name": "notion-knowledge-capture (Codex)",
        "Description": "Capture conversations and decisions into Notion pages from Cursor/tulsCodex.",
        "Category": "Notion/Data",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/notion-knowledge-capture/SKILL.md",
        "Version": "",
        "Tags": ["notion"],
    },
    {
        "Name": "develop-web-game",
        "Description": "Build and iterate web games (HTML/JS) with Playwright test loop, screenshots, and console error review.",
        "Category": "Coding/Engineering",
        "Platform": "Cursor",
        "Status": "Active",
        "Location": "codex-skills",
        "File Path": f"{BASE}/.codex/skills/develop-web-game/SKILL.md",
        "Version": "",
        "Tags": [],
    },
]


def make_page(skill: dict) -> dict:
    tags = skill.get("Tags", [])
    props = {
        "Name": {"title": [{"text": {"content": skill["Name"]}}]},
        "Description": {"rich_text": [{"text": {"content": skill["Description"]}}]},
        "Category": {"select": {"name": skill["Category"]}},
        "Platform": {"select": {"name": skill["Platform"]}},
        "Status": {"select": {"name": skill["Status"]}},
        "Location": {"select": {"name": skill["Location"]}},
        "File Path": {"rich_text": [{"text": {"content": skill["File Path"]}}]},
    }
    if skill.get("Version"):
        props["Version"] = {"rich_text": [{"text": {"content": skill["Version"]}}]}
    if tags:
        props["Tags"] = {"multi_select": [{"name": t} for t in tags]}
    return props


inserted = 0
errors = 0

for skill in SKILLS:
    try:
        notion.pages.create(
            parent={"database_id": DB_ID},
            properties=make_page(skill),
        )
        print(f"  ✓ {skill['Name']}")
        inserted += 1
    except Exception as e:
        print(f"  ✗ {skill['Name']}: {e}")
        errors += 1

print(f"\nDone: {inserted} inserted, {errors} errors")
